module.exports=[{"label": "hammem lif",value: "hammem lif"},
{"label": "mornag",value: "mornag"},
{"label": "Ben Arous",value: "Ben Arous"},
{"label": "bou mhel el bassatine",value: "bou mhel el bassatine"},
{"label": "ez-zahra",value: "ez-zahra"},
{"label": "mohamedia",value: "mohamedia"},
{"label": "Khelidia",value: "Khelidia"},
{"label": "rades",value: "rades"},
{"label": "el mourouj",value: "el mourouj"},
{"label": "fouchana",value: "fouchana"},
{"label": "hammem chatt",value: "hammem chatt"},
{"label": "megrine",value: "megrine"},
{"label": "Naassen",value: "Nâassen"},
{"label": "tameghza",value: "tameghza"},
{"label": "deguach",value: "deguach"},
{"label": "Tozeur",value: "Tozeur"},
{"label": "hazoua",value: "hazoua"},
{"label": "nefta",value: "nefta"},
{"label": "hamet ejrid",value: "hamet ejrid"},
{"label": "mednine",value: "mednine"},
{"label": "beni-khedech",value: "beni-khedech"},
{"label": "zarzis",value: "zarzis"},
{"label": "ben guerdane",value: "ben guerdane"},
{"label": "zarzis nord",value: "zarzis nord"},
{"label": "sidi makhlouf",value: "sidi makhlouf"},
{"label": "bou-ghrara",value: "bou-ghrara"},
{"label": "ajim",value: "ajim"},
{"label": "houmet essouk",value: "houmet essouk"},
{"label": "midoun",value: "midoun"},
{"label": "Monastir",value: "Monastir"},
{"label": "ouerdanine",value: "ouerdanine"},
{"label": "sidi ameur masjed aïssa",value: "sidi ameur masjed aïssa"},
{"label": "menzel harb",value: "menzel harb"},
{"label": "zaouiet kontoch",value: "zaouiet kontoch"},
{"label": "ksibet el mediouni",value: "ksibet el mediouni"},
{"label": "menzel kamel",value: "menzel kamel"},
{"label": "jamel",value: "jamel"},
{"label": "menzel hayet",value: "menzel hayet"},
{"label": "zeramdine",value: "zeramdine"},
{"label": "ghnada",value: "ghnada"},
{"label": "beni hassen",value: "beni hassen"},
{"label": "menzel farsi",value: "menzel farsi"},
{"label": "moknine",value: "moknine"},
{"label": "amiret touazra",value: "amiret touazra"},
{"label": "benen bodher",value: "benen bodher"},
{"label": "bou-hjar",value: "bou-hjar"},
{"label": "ksar hlel",value: "ksar hlel"},
{"label": "bekalta",value: "bekalta"},
{"label": "amiret el hojjaj",value: "amiret el hojjaj"},
{"label": "menzel en-nour",value: "menzel en-nour"},
{"label": "bembla el manara",value: "bembla el manara"},
{"label": "lamta",value: "lamta"},
{"label": "sidi bennour",value: "sidi bennour"},
{"label": "cherahil",value: "cherahil"},
{"label": "sahline",value: "sahline"},
{"label": "amiret el fehoul",value: "amiret el fehoul"},
{"label": "touza",value: "touza"},
{"label": "khenis",value: "khenis"},
{"label": "tebolba",value: "tebolba"},
{"label": "sayada",value: "sayada"},
{"label": "faouar",value: "faouar"},
{"label": "douz",value: "douz"},
{"label": "rejim mâatoug",value: "rejim mâatoug"},
{"label": "Kebili",value: "Kebili"},
{"label": "fatnassa",value: "fatnassa"},
{"label": "bechelli",value: "bechelli"},
{"label": "el golaa",value: "el golaa"},
{"label": "jemna",value: "jemna"},
{"label": "souk el ahed",value: "souk el ahed"},
{"label": "oum el araies",value: "oum el araies"},
{"label": "Gafsa",value: "Gafsa"},
{"label": "redeyef",value: "redeyef"},
{"label": "metlaoui",value: "metlaoui"},
{"label": "sned",value: "sned"},
{"label": "sanouche",value: "sanouche"},
{"label": "el ksar",value: "el ksar"},
{"label": "el guetar",value: "el guetar"},
{"label": "mdhila",value: "mdhila"},
{"label": "lala",value: "lala"},
{"label": "sidi aïch",value: "sidi aïch"},
{"label": "sidi boubaker",value: "sidi boubaker"},
{"label": "belkhir",value: "belkhir"},
{"label": "dhehbia",value: "dhehbia"},
{"label": "remada",value: "remada"},
{"label": "Tataouine",value: "Tataouine"},
{"label": "smar",value: "smar"},
{"label": "ghomrassen",value: "ghomrassen"},
{"label": "chenini eddouiret",value: "chenini eddouiret"},
{"label": "bir lahmar",value: "bir lahmar"},
{"label": "khemaïria",value: "khemaïria"},
{"label": "aïn drahem",value: "aïn drahem"},
{"label": "beni m'tir",value: "beni m'tir"},
{"label": "oued meliz",value: "oued meliz"},
{"label": "balta bou aouane",value: "balta bou aouane"},
{"label": "ghardimaou",value: "ghardimaou"},
{"label": "Jendouba",value: "Jendouba"},
{"label": "el galaa el mâaden forgassen",value: "el galaa el mâaden forgassen"},
{"label": "bou salem",value: "bou salem"},
{"label": "ettataouer",value: "ettataouer"},
{"label": "jaouaouada",value: "jaouaouada"},
{"label": "fernana",value: "fernana"},
{"label": "nadhour",value: "nadhour"},
{"label": "tabarka",value: "tabarka"},
{"label": "ousja",value: "ousja"},
{"label": "ghar el meleh",value: "ghar el meleh"},
{"label": "rafraf",value: "rafraf"},
{"label": "menzel djemil",value: "menzel djemil"},
{"label": "tinja",value: "tinja"},
{"label": "menzel bourguiba",value: "menzel bourguiba"},
{"label": "ras el djebel",value: "ras el djebel"},
{"label": "metline",value: "metline"},
{"label": "Bizerte",value: "Bizerte"},
{"label": "el alia",value: "el alia"},
{"label": "el hachachna",value: "el hachachna"},
{"label": "djoumine",value: "djoumine"},
{"label": "sedjnane",value: "sedjnane"},
{"label": "ghezala",value: "ghezala"},
{"label": "mateur",value: "mateur"},
{"label": "utique",value: "utique"},
{"label": "menzel abderrahmen",value: "menzel abderrahmen"},
{"label": "el hamma",value: "el hamma"},
{"label": "menzel el habib",value: "menzel el habib"},
{"label": "dekhilet toujane",value: "dekhilet toujane"},
{"label": "nouvelle matmata",value: "nouvelle matmata"},
{"label": "ketana",value: "ketana"},
{"label": "teboulbou",value: "teboulbou"},
{"label": "mareth",value: "mareth"},
{"label": "ezzarat",value: "ezzarat"},
{"label": "matmata",value: "matmata"},
{"label": "ouedhref",value: "ouedhref"},
{"label": "el metouia",value: "el metouia"},
{"label": "chenini nahal",value: "chenini nahal"},
{"label": "bou-chemma",value: "bou-chemma"},
{"label": "ghanouch",value: "ghanouch"},
{"label": "Gabes",value: "Gabes"},
{"label": "habib thameur",value: "habib thameur"},
{"label": "la marsa",value: "la marsa"},
{"label": "le kram",value: "le kram"},
{"label": "le bardo",value: "le bardo"},
{"label": "sidi hassine",value: "sidi hassine"},
{"label": "carthage",value: "carthage"},
{"label": "sidi bou saïd",value: "sidi bou saïd"},
{"label": "la goulette",value: "la goulette"},
{"label": "Tunis",value: "Tunis"},
{"label": "el hekaima",value: "el hekaima"},
{"label": "Mahdia",value: "Mahdia"},
{"label": "rejiche",value: "rejiche"},
{"label": "talalsa",value: "talalsa"},
{"label": "bou merdes",value: "bou merdes"},
{"label": "el bradâa",value: "el bradâa"},
{"label": "chebba",value: "chebba"},
{"label": "zalba",value: "zalba"},
{"label": "essouassi",value: "essouassi"},
{"label": "kerker",value: "kerker"},
{"label": "hebira",value: "hebira"},
{"label": "chorbane",value: "chorbane"},
{"label": "sidi zid",value: "sidi zid"},
{"label": "ouled chamekh",value: "ouled chamekh"},
{"label": "sidi alouane",value: "sidi alouane"},
{"label": "ksour essaf",value: "ksour essaf"},
{"label": "melloulech",value: "melloulech"},
{"label": "el djem",value: "el djem"},
{"label": "er-rouhia",value: "er-rouhia"},
{"label": "el hababsa",value: "el hababsa"},
{"label": "gâafour",value: "gâafour"},
{"label": "bouarada",value: "bouarada"},
{"label": "el aroussa",value: "el aroussa"},
{"label": "bourouis",value: "bourouis"},
{"label": "el krib",value: "el krib"},
{"label": "Siliana",value: "Siliana"},
{"label": "sidi morched",value: "sidi morched"},
{"label": "makthar",value: "makthar"},
{"label": "bargou",value: "bargou"},
{"label": "kesra",value: "kesra"},
{"label": "tazaghrane",value: "tazaghrane"},
{"label": "el haouaria",value: "el haouaria"},
{"label": "azmour",value: "azmour"},
{"label": "hammam el guezaz",value: "hammam el guezaz"},
{"label": "menzel horr",value: "menzel horr"},
{"label": "takelsa",value: "takelsa"},
{"label": "menzel bou zelfa",value: "menzel bou zelfa"},
{"label": "el mida",value: "el mida"},
{"label": "soliman",value: "soliman"},
{"label": "bou argoub",value: "bou argoub"},
{"label": "beni khalled",value: "beni khalled"},
{"label": "korba",value: "korba"},
{"label": "dar châabane",value: "dar châabane"},
{"label": "el mâamoura",value: "el mâamoura"},
{"label": "tazerka",value: "tazerka"},
{"label": "beni khiar",value: "beni khiar"},
{"label": "hammamet",value: "hammamet"},
{"label": "Nabeul",value: "Nabeul"},
{"label": "zaouiet djedidi",value: "zaouiet djedidi"},
{"label": "dar allouch",value: "dar allouch"},
{"label": "menzel temim",value: "menzel temim"},
{"label": "bou charray ech-cherifet",value: "bou charray ech-cherifet"},
{"label": "fondouk djedid",value: "fondouk djedid"},
{"label": "kelibia",value: "kelibia"},
{"label": "korbus",value: "korbus"},
{"label": "sidi djedidi",value: "sidi djedidi"},
{"label": "grombalia",value: "grombalia"},
{"label": "somâa",value: "somâa"},
{"label": "nefza",value: "nefza"},
{"label": "ouachtata",value: "ouachtata"},
{"label": "zahret medien",value: "zahret medien"},
{"label": "Beja",value: "Beja"},
{"label": "el mâagoula",value: "el mâagoula"},
{"label": "sidi smaîl",value: "sidi smaîl"},
{"label": "testour",value: "testour"},
{"label": "medjez el bab",value: "medjez el bab"},
{"label": "goubellat",value: "goubellat"},
{"label": "es-slouguia",value: "es-slouguia"},
{"label": "tibar",value: "tibar"},
{"label": "teboursouk",value: "teboursouk"},
{"label": "sidi bou ali",value: "sidi bou ali"},
{"label": "kalâa kebira",value: "kalâa kebira"},
{"label": "sidi el heni",value: "sidi el heni"},
{"label": "ezzouhour",value: "ezzouhour"},
{"label": "msaken",value: "msaken"},
{"label": "Sousse",value: "Sousse"},
{"label": "akouda",value: "akouda"},
{"label": "kalâa seghira",value: "kalâa seghira"},
{"label": "chott meriam",value: "chott meriam"},
{"label": "Messaadine",value: "Messaadine"},
{"label": "hammam Sousse",value: "hammam Sousse"},
{"label": "bouficha",value: "bouficha"},
{"label": "zaouit Sousse",value: "zaouit Sousse"},
{"label": "ksibet thrayet",value: "ksibet thrayet"},
{"label": "enfidha",value: "enfidha"},
{"label": "gerimet",value: "gerimet"},
{"label": "hergla",value: "hergla"},
{"label": "kondar",value: "kondar"},
{"label": "Kalaat El Andalous",value: "Kalaat El Andalous"},
{"label": "Sidi Thabet",value: "Sidi Thabet"},
{"label": "Raoued",value: "Raoued"},
{"label": "Ariana",value: "Ariana"},
{"label": "Soukra",value: "Soukra"},
{"label": "El Mnihla",value: "El Mnihla"},
{"label": "Ettadhamen",value: "Ettadhamen"},
{"label": "el battane",value: "el battane"},
{"label": "tebourba",value: "tebourba"},
{"label": "djedaïda",value: "djedaïda"},
{"label": "den-den",value: "den-den"},
{"label": "douar hicher",value: "douar hicher"},
{"label": "mornaguia",value: "mornaguia"},
{"label": "el bassatine",value: "el bassatine"},
{"label": "borj el amri",value: "borj el amri"},
{"label": "oued ellil",value: "oued ellil"},
{"label": "Manouba",value: "Manouba"},
{"label": "skhira",value: "skhira"},
{"label": "bir ali ben khelifa",value: "bir ali ben khelifa"},
{"label": "agareb",value: "agareb"},
{"label": "el hajeb",value: "el hajeb"},
{"label": "Sfax",value: "Sfax"},
{"label": "sakiet eddaier",value: "sakiet eddaier"},
{"label": "sakiet ezzit",value: "sakiet ezzit"},
{"label": "el ghraiba",value: "el ghraiba"},
{"label": "el aïn",value: "el aïn"},
{"label": "gremda",value: "gremda"},
{"label": "el aouabed khazanet",value: "el aouabed khazanet"},
{"label": "mahres",value: "mahres"},
{"label": "hazeg el louza",value: "hazeg el louza"},
{"label": "el achech",value: "el achech"},
{"label": "el amra",value: "el amra"},
{"label": "tina",value: "tina"},
{"label": "kerkenah",value: "kerkenah"},
{"label": "chihia",value: "chihia"},
{"label": "en-nadhour sidi ali belabed",value: "en-nadhour sidi ali belabed"},
{"label": "menzel chaker",value: "menzel chaker"},
{"label": "el hencha",value: "el hencha"},
{"label": "en-nasr",value: "en-nasr"},
{"label": "djebeniana",value: "djebeniana"},
{"label": "Zaghouan",value: "Zaghouan"},
{"label": "jebel oust",value: "jebel oust"},
{"label": "el fahs",value: "el fahs"},
{"label": "bir m'chergua",value: "bir m'chergua"},
{"label": "el amiem",value: "el amiem"},
{"label": "en nadhour",value: "en nadhour"},
{"label": "ez zeriba",value: "ez zeriba"},
{"label": "saouef",value: "saouef"},
{"label": "Kairouan",value: "Kairouan"},
{"label": "echbika",value: "echbika"},
{"label": "aîn djeloula",value: "aîn djeloula"},
{"label": "hafouz",value: "hafouz"},
{"label": "el alâa",value: "el alâa"},
{"label": "chaouachi",value: "chaouachi"},
{"label": "el aîn el beidha",value: "el aîn el beidha"},
{"label": "abida",value: "abida"},
{"label": "El Ooueslatia",value: "El Ooueslatia"},
{"label": "bouhajla",value: "bouhajla"},
{"label": "menzel mhiri",value: "menzel mhiri"},
{"label": "hajeb el ayoun",value: "hajeb el ayoun"},
{"label": "jehina",value: "jehina"},
{"label": "nasrallah",value: "nasrallah"},
{"label": "cheraitia",value: "cheraitia"},
{"label": "echrarda",value: "echrarda"},
{"label": "sbikha",value: "sbikha"},
{"label": "sisseb",value: "sisseb"},
{"label": "rakada",value: "rakada"},
{"label": "touiref",value: "touiref"},
{"label": "nebeur",value: "nebeur"},
{"label": "sakiet sidi youssef",value: "sakiet sidi youssef"},
{"label": "kalâat snan",value: "kalâat snan"},
{"label": "Le Kef",value: "Le Kef"},
{"label": "dahmani",value: "dahmani"},
{"label": "zâafrane dyr el Le Kef",value: "zâafrane dyr el Le Kef"},
{"label": "menzel salem",value: "menzel salem"},
{"label": "tajerouine",value: "tajerouine"},
{"label": "es-sers",value: "es-sers"},
{"label": "el ksour",value: "el ksour"},
{"label": "kalâat khasba",value: "kalâat khasba"},
{"label": "djerissa",value: "djerissa"},
{"label": "bahra",value: "bahra"},
{"label": "el marja",value: "el marja"},
{"label": "regueb",value: "regueb"},
{"label": "souk jedid",value: "souk jedid"},
{"label": "Sidi Bouzid",value: "Sidi Bouzid"},
{"label": "el ahouaz",value: "el ahouaz"},
{"label": "jilma",value: "jilma"},
{"label": "bennour",value: "bennour"},
{"label": "baten elghezel",value: "baten elghezel"},
{"label": "cebalet ouled asker",value: "cebalet ouled asker"},
{"label": "bir el hafey",value: "bir el hafey"},
{"label": "menzel bouzaiane",value: "menzel bouzaïane"},
{"label": "meknassy",value: "meknassy"},
{"label": "mezzouna",value: "mezzouna"},
{"label": "rahal",value: "rahal"},
{"label": "el mansoura",value: "el mansoura"},
{"label": "ouled haffouz",value: "ouled haffouz"},
{"label": "essaida",value: "essaïda"},
{"label": "sidi ali ben aoun",value: "sidi ali ben aoun"},
{"label": "ennour",value: "ennour"},
{"label": "el ayoun",value: "el ayoun"},
{"label": "ech-chraya machrek ech-chams",value: "ech-chraya machrek ech-chams"},
{"label": "aïn el khemaïssia",value: "aïn el khemaïssia"},
{"label": "djedeliane",value: "djedeliane"},
{"label": "thala",value: "thala"},
{"label": "hidra",value: "hidra"},
{"label": "feriana",value: "feriana"},
{"label": "telept",value: "telept"},
{"label": "majel bel abbes",value: "majel bel abbes"},
{"label": "sbeitla",value: "sbeitla"},
{"label": "sbiba",value: "sbiba"},
{"label": "foussana",value: "foussana"},
{"label": "hassi el ferid",value: "hassi el ferid"},
{"label": "Kasserine",value: "Kasserine"},
{"label": "bouzguam",value: "bouzguam"},
{"label": "errakhmet",value: "errakhmet"},
{"label": "Ezzouhour",value: "Ezzouhour"},
{"label": "khmouda",value: "khmouda"}]